"""
For finetuning a custom retriever.
"""

# RetrieverTrainingArguments
model_name_or_path: "facebook/contriever-msmarco"
hf_dataset_name: "ms2"

# TrainingArguments
do_train: true
do_eval: true
learning_rate: 1e-4
num_train_epochs: 30
per_device_train_batch_size: 64
per_device_eval_batch_size: 1
weight_decay: 0.01